[package]
name = "loan-payoff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.6"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
test-case = "1.2.3"
